#include <arena.c>
#include <ast_utils/ast_msg.c>
#include <ast_utils/did_you_mean.c>
#include <ast_utils/sizeof.c>
#include <ast_utils/symbol_collection_clone.c>
#include <ast_utils/symbol_table.c>
#include <ast_utils/tast_print.c>
#include <ast_utils/tast_utils.c>
#include <ast_utils/uast_clone.c>
#include <ast_utils/uast_print.c>
#include <ast_utils/uast_utils.c>
#include <main.c>
#include <error_msg.c>
#include <globals.c>
#include <lang_type/ir_lang_type_after.c>
#include <lang_type/ir_lang_type_print.c>
#include <lang_type/lang_type_after.c>
#include <lang_type/lang_type_from_ulang_type.c>
#include <lang_type/lang_type_print.c>
#include <lang_type/ulang_type_is_equal.c>
#include <lang_type/ulang_type_print.c>
#include <lang_type/ulang_type_serialize.c>
#include <name.c>
#include <str_and_num_utils.c>
#include <util/cfg.c>
#include <util/file.c>
#include <util/ir_operator_type.c>
#include <util/newstring.c>
#include <util/operator_type.c>
#include <util/parameters.c>
#include <util/params_log_level.c>
