#include <codegen/codegen_common.c>
#include <codegen/emit_c.c>
#include <codegen/emit_llvm.c>
#include <ir/add_load_and_store.c>
#include <ir/check_uninitialized.c>
#include <ir/construct_cfgs.c>
#include <ir/ir_graphvis.c>
#include <ir/ir_print.c>
#include <ir/ir_utils.c>
#include <ir/remove_void_assigns.c>
