#ifndef EXPECTED_FAIL_TYPE_H
#define EXPECTED_FAIL_TYPE_H

typedef enum {
    EXPECT_FAIL_TYPE_NONE,
    EXPECT_FAIL_UNDEFINED_SYMBOL,
    EXPECT_FAIL_UNDEFINED_FUNCTION,
    EXPECT_FAIL_EXPECTED_EXPRESSION,
    EXPECT_FAIL_INCOMPLETE_VAR_DEF,
    EXPECT_FAIL_BINARY_MISMATCHED_TYPES,
    EXPECT_FAIL_ASSIGNMENT_MISMATCHED_TYPES,
    EXPECT_FAIL_INVALID_FUN_ARG,
    EXPECT_FAIL_INVALID_COUNT_FUN_ARGS,
    EXPECT_FAIL_MISSING_RETURN_STATEMENT,
    EXPECT_FAIL_REDEFINITION_SYMBOL,
    EXPECT_FAIL_INVALID_STRUCT_MEMBER,
    EXPECT_FAIL_INVALID_STRUCT_MEMBER_IN_LITERAL,
    EXPECT_FAIL_MISMATCHED_RETURN_TYPE,
    EXPECT_FAIL_PARSER_EXPECTED,
    EXPECT_FAIL_MISSING_CLOSE_CURLY_BRACE,
    EXPECT_FAIL_INVALID_TOKEN,
    EXPECT_FAIL_INVALID_EXTERN_TYPE,
} EXPECT_FAIL_TYPE;

#endif // EXPECTED_FAIL_TYPE_H
