#include <name.c>
#include <str_and_num_utils.c>
#include <main.c>
#include <arena.c>
#include <ast_utils/uast_print.c>
#include <ast_utils/tast_print.c>
#include <ast_utils/tast_utils.c>
#include <lang_type/lang_type_after.c>
#include <lang_type/ir_lang_type_after.c>
#include <ir/ir_print.c>
#include <ir/remove_void_assigns.c>
#include <ir/check_uninitialized.c>
#include <ir/construct_cfgs.c>
#include <lang_type/lang_type_print.c>
#include <lang_type/ir_lang_type_print.c>
#include <lang_type/ulang_type_print.c>
#include <globals.c>
#include <ast_utils/uast_utils.c>
#include <ast_utils/symbol_table.c>
#include <util/file.c>
#include <util/parameters.c>
#include <util/operator_type.c>
#include <util/ir_operator_type.c>
#include <util/params_log_level.c>
#include <util/cfg.c>
#include <util/newstring.c>
#include <error_msg.c>
#include <lang_type/ulang_type_serialize.c>
#include <lang_type/lang_type_from_ulang_type.c>
#include <lang_type/ulang_type_is_equal.c>
#include <ast_utils/uast_clone.c>
#include <ast_utils/did_you_mean.c>
#include <ast_utils/ast_msg.c>
#include <ast_utils/symbol_collection_clone.c>
#include <sema/uast_expr_to_ulang_type.c>
#include <sema/check_gen_constraints.c>
#include <sema/type_checking.c>
#include <sema/expand_lang_def.c>
#include <sema/expand_using.c>
#include <sema/check_general_assignment.c>
#include <sema/resolve_generics.c>
#include <sema/generic_sub.c>
#include <sema/infer_generic_type.c>
#include <sema/check_struct_recursion.c>
#include <ast_utils/sizeof.c>
#include <token/token.c>
#include <token/tokenizer.c>
#include <parser.c>
#include <ir/add_load_and_store.c>
#include <codegen/codegen_common.c>
#include <codegen/emit_llvm.c>
#include <codegen/emit_c.c>
#include <ir/ir_utils.c>
#include <ir/ir_graphvis.c>
